[[https://stable.melpa.org/#/base16-theme][file:https://stable.melpa.org/packages/base16-theme-badge.svg]]
[[http://melpa.org/#/base16-theme][file:http://melpa.org/packages/base16-theme-badge.svg]]

* Base16 themes for Emacs

[[https://github.com/chriskempson/base16][Base16]] provides carefully chosen syntax highlighting and a default set
of sixteen colors suitable for a wide range of applications. Base16 is
not a single theme but a set of guidelines with numerous
implementations.

This repository contains the Emacs templates and [[http://melpa.org/#/base16-theme][MELPA]]. It can be built
by using one of the builders listed on the main Base16 page.

If you notice anything that looks strange or if this repo is missing
any scheme updates, please feel free to open an issue or submit a pull
request.

** Previews

Theme previews can be found [[https://belak.github.io/base16-emacs/][here]]. The generator can be found on the
gh-pages branch, so if you have ideas for improvements, they can go
there.

** evil-mode

=evil-mode= doesn't provide a way for themes to set the cursor color,
so if you're interested in matching the base16 spaceline indicator,
you can use the following snippet:

#+begin_src emacs-lisp
  ;; Set the cursor color based on the evil state
  (defvar my/base16-colors base16-default-dark-colors)
  (setq evil-emacs-state-cursor   `(,(plist-get my/base16-colors :base0D) box)
        evil-insert-state-cursor  `(,(plist-get my/base16-colors :base0D) bar)
        evil-motion-state-cursor  `(,(plist-get my/base16-colors :base0E) box)
        evil-normal-state-cursor  `(,(plist-get my/base16-colors :base0B) box)
        evil-replace-state-cursor `(,(plist-get my/base16-colors :base08) bar)
        evil-visual-state-cursor  `(,(plist-get my/base16-colors :base09) box))
#+end_src

* Credits

Current maintainer: [[https://github.com/belak][belak]]

Previous maintainers:

- [[https://github.com/mkaito][mkaito]]
- [[https://github.com/neil477][neil477]]
